name: PG-18
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f4'
    - '#ac828c'
    - '#1b1519'
    - '#504253'
    - '#dd6442'
  brandStrength: 0.7609686818905175
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
