name: PG-18
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02807
title: "Pommegenozide's Dark Room"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffbf'
    - '#f9b89a'
    - '#945d48'
    - '#f21604'
    - '#33170c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
